name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' 

    - name: Install numpy
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check numpy version
      run: |
        python -c "import numpy; assert numpy.__version__ == '1.26.1', f'Numpy version is {numpy.__version__}'"
        
    - name: Check output
      run: |
        output=$(python main.py)
        expected_output="[1 2 3 4 5 6 7 8 9 10]"
        if [[ "$output" != "$expected_output" ]]; then
          echo "Output is $output, but expected $expected_output"
          exit 1
        fi
