name: Check Virtual Environment Setup

on: [push, pull_request]

jobs:
  check-virtualenv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for conda environment
        run: |
          if [ -f "environment.yml" ]; then
            echo "conda environment detected."
            echo "CONDA_ENV=true" >> $GITHUB_ENV
          else
            echo "No conda environment found."
            echo "CONDA_ENV=false" >> $GITHUB_ENV
          fi
      
      - name: Check for venv environment (venv/bin/activate)
        run: |
          if [ -f "venv/bin/activate" ]; then
            echo "venv environment detected (venv/bin/activate)."
            echo "VENV_ENV=true" >> $GITHUB_ENV
          else
            echo "No venv environment found in venv/bin/activate."
            echo "VENV_ENV=false" >> $GITHUB_ENV
          fi
      
      - name: Check for venv environment (.venv/Scripts/activate)
        run: |
          if [ -f ".venv/Scripts/activate" ]; then
            echo "venv environment detected (.venv/Scripts/activate)."
            echo "VENV_ALT_ENV=true" >> $GITHUB_ENV
          else
            echo "No venv environment found in .venv/Scripts/activate."
            echo "VENV_ALT_ENV=false" >> $GITHUB_ENV
          fi
      
      - name: Fail if no environment is found
        run: |
          if [[ "$CONDA_ENV" == "false" && "$VENV_ENV" == "false" && "$VENV_ALT_ENV" == "false" ]]; then
            echo "Error: No virtual environment detected. Workflow failed."
            exit 1
          fi